"""Renew the long-lived Instagram/Facebook access token BEFORE it expires.

WHY (2026-08-24): Meta long-lived user tokens last 60 days. Ours expired on
18-Aug-26 and auto-publish silently posted nothing for a week. Meta lets a
still-VALID long-lived token be exchanged for a fresh 60-day one — but an
already-expired token can never be refreshed. So this runs weekly from
.github/workflows/refresh_ig_token.yml and, when the token has < 30 days left,
exchanges it and writes the new value back to the INSTAGRAM_ACCESS_TOKEN
GitHub secret.

Needs (all GitHub secrets):
  INSTAGRAM_ACCESS_TOKEN  current, still-valid long-lived token
  FB_APP_ID               Meta app id ("Gen Z publisher" = 989601526736983)
  FB_APP_SECRET           Meta app secret (App Dashboard → Settings → Basic)
  ACTIONS_SECRETS_PAT     GitHub PAT with `repo` scope so the workflow can
                          update the secret (GITHUB_TOKEN cannot write secrets)

Prints the new token to stdout ONLY when --print is passed (the workflow pipes
it straight into `gh secret set`); otherwise never logs token values.
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone

import requests

GRAPH = "https://graph.facebook.com/v21.0"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--min-days", type=int, default=30,
                    help="Only refresh when fewer than this many days remain.")
    ap.add_argument("--force", action="store_true", help="Refresh regardless.")
    ap.add_argument("--print", action="store_true",
                    help="Write the NEW token to stdout (for `gh secret set`).")
    args = ap.parse_args()

    tok = os.getenv("INSTAGRAM_ACCESS_TOKEN", "")
    app_id = os.getenv("FB_APP_ID", "")
    app_secret = os.getenv("FB_APP_SECRET", "")
    if not tok:
        print("FAIL: INSTAGRAM_ACCESS_TOKEN not set", file=sys.stderr)
        return 1
    if not app_id or not app_secret:
        print("SKIP: FB_APP_ID / FB_APP_SECRET not set — cannot refresh. "
              "Add both as GitHub secrets.", file=sys.stderr)
        return 3

    r = requests.get(f"{GRAPH}/debug_token",
                     params={"input_token": tok, "access_token": tok}, timeout=30)
    js = r.json()
    data = js.get("data") or {}
    if js.get("error") or not data.get("is_valid"):
        print(f"FAIL: current token is already invalid/expired — Meta cannot "
              f"refresh a dead token. A NEW token must be generated by hand: "
              f"{js.get('error') or data}", file=sys.stderr)
        return 1
    exp = int(data.get("expires_at") or 0)
    days = (datetime.fromtimestamp(exp, tz=timezone.utc)
            - datetime.now(timezone.utc)).days if exp else 10**6
    print(f"Current token valid, ~{days} day(s) left.", file=sys.stderr)
    if not args.force and days >= args.min_days:
        print("OK: nothing to do yet.", file=sys.stderr)
        return 0

    r = requests.get(f"{GRAPH}/oauth/access_token", params={
        "grant_type": "fb_exchange_token",
        "client_id": app_id,
        "client_secret": app_secret,
        "fb_exchange_token": tok,
    }, timeout=30)
    js = r.json()
    new = js.get("access_token")
    if not new:
        print(f"FAIL: exchange rejected: {js}", file=sys.stderr)
        return 1
    print(f"OK: new long-lived token issued (expires_in={js.get('expires_in')}s).",
          file=sys.stderr)
    if args.print:
        sys.stdout.write(new)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
